# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stakz < Formula
  desc "Simple local command runner and file server compatible with stakz.dev"
  homepage "https://stakz.dev"
  version "0.1.0"
  license "MIT"

  depends_on "git" if OS.mac?
  depends_on "zsh" => :optional

  on_macos do
    on_intel do
      url "https://github.com/writeabyte/stakz-server/releases/download/v0.1.0/stakz-server_Darwin_x86_64.tar.gz"
      sha256 "58d5ed1e56c9935c20c58f3b67f23f87f6b79169e087fede767a07256a310733"

      def install
        bin.install "stakz"
      end
    end
    on_arm do
      url "https://github.com/writeabyte/stakz-server/releases/download/v0.1.0/stakz-server_Darwin_arm64.tar.gz"
      sha256 "e46217329939e7d05b8bc7fa2a5f21cd160fc03be9f03aab0266ab707ff9809f"

      def install
        bin.install "stakz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/writeabyte/stakz-server/releases/download/v0.1.0/stakz-server_Linux_x86_64.tar.gz"
        sha256 "cb47b246170181e173f96740d8782ca72f3aaab571cddccfe48147b402dd25e9"

        def install
          bin.install "stakz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/writeabyte/stakz-server/releases/download/v0.1.0/stakz-server_Linux_arm64.tar.gz"
        sha256 "60198d860c5d68361b8d8a38b105b5099c7ba26cff07b0296b1ccc9459f45772"

        def install
          bin.install "stakz"
        end
      end
    end
  end
end
