# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stakz < Formula
  desc "Simple local command runner and file server compatible with stakz.dev"
  homepage "https://stakz.dev"
  version "0.1.0"
  license "MIT"

  depends_on "git" if OS.mac?
  depends_on "zsh" => :optional

  on_macos do
    on_intel do
      url "https://github.com/writeabyte/homebrew-stakz/releases/download/v0.1.0/stakz-server_Darwin_x86_64.tar.gz"
      sha256 "dd760f8e613e946c9c510013de0f667f6055db8d1191471ca9f738cd5628cd95"

      def install
        bin.install "stakz"
      end
    end
    on_arm do
      url "https://github.com/writeabyte/homebrew-stakz/releases/download/v0.1.0/stakz-server_Darwin_arm64.tar.gz"
      sha256 "bcdcdf6199eed4e5718ee6810fcab94be3458e7aa27cdbbf8a5968ee841996dc"

      def install
        bin.install "stakz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/writeabyte/homebrew-stakz/releases/download/v0.1.0/stakz-server_Linux_x86_64.tar.gz"
        sha256 "6da6d86a0be8ea86b836372735081b547ac2498c58d557300b7a5d20fd43dd44"

        def install
          bin.install "stakz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/writeabyte/homebrew-stakz/releases/download/v0.1.0/stakz-server_Linux_arm64.tar.gz"
        sha256 "71165c24cbcd5ad7ce7349e61e9fa1e779e8b0f533680d06f245804f1e08ec0f"

        def install
          bin.install "stakz"
        end
      end
    end
  end
end
